// <auto-generated />
using System;
using BlazorApp.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorApp.Server.Models.Diary", b =>
                {
                    b.Property<int>("DiaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("DiaryID");

                    b.HasIndex("UserID");

                    b.ToTable("Diaries");

                    b.HasData(
                        new
                        {
                            DiaryID = 1,
                            Date = new DateTime(2020, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Today i have guests at home",
                            Title = "At Home"
                        },
                        new
                        {
                            DiaryID = 2,
                            Date = new DateTime(2020, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Today i created an blazor project",
                            Title = "At Work"
                        });
                });

            modelBuilder.Entity("BlazorApp.Server.Models.Todo", b =>
                {
                    b.Property<int>("TodoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TodoID");

                    b.HasIndex("UserID");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            TodoID = 1,
                            Date = new DateTime(2020, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "List of products that i need to buy ...",
                            Title = "Shopping"
                        },
                        new
                        {
                            TodoID = 2,
                            Date = new DateTime(2020, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adress here",
                            Title = "Meet friends"
                        });
                });

            modelBuilder.Entity("BlazorApp.Server.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "samir.jan@gmail.com",
                            FirstName = "Samir",
                            LastName = "Jan",
                            Password = "Samir123"
                        });
                });

            modelBuilder.Entity("BlazorApp.Server.Models.Diary", b =>
                {
                    b.HasOne("BlazorApp.Server.Models.User", null)
                        .WithMany("Diaries")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("BlazorApp.Server.Models.Todo", b =>
                {
                    b.HasOne("BlazorApp.Server.Models.User", null)
                        .WithMany("Todos")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
